### ISSUE TITLE
Organize the tensorflow repo and clean up

### ISSUE THREAD

**Issue by JosephKnecht-lab** [UniversalDot/tensorflow#9]
All code for generating the models should be made available publicly on GitHub. 

The following requirements should be satisfied:

- [x] Add comments where is needed
- [x] No local paths  (anyone should be able to run and generate the models)
- [x] Save the model in saved_model zip format
- [x] When generating the model, we should be able to specify the model version. This model version saves the model in a new version folder. Example: model 1 should be saved in folder /1/

**Comment by VittorioRossi** [comment]
All the files relative to the model creation have been pushed in the model_creation folder

**Comment by JosephKnecht-lab** [comment]
I can run the `create_model.ipynb` but it does not generate a zip file for me. Am I missing some parameters that should be configured? 

Also, this is the scann model? how about the labse and bart?

**Comment by VittorioRossi** [comment]
Try now using the function `jobdesc_create_save()`. It is a wrapper around the `create_save` function, but with the Universal Sentence Encoder and the embedding of the extracted job_desc datast.

For now we are using Universal Sentence Encoder because is compatible with tensorflow. For labse and bart we need to find a way to make them compatible with tf as well. 

I also pushed the dataset with the the dataset with the [keyword extraction for jobdesc](https://github.com/UniversalDot/tensorflow/blob/develop/dataset/jobdesc_key.csv) and the [embeddings] (https://github.com/UniversalDot/tensorflow/tree/develop/dataset/key_embeddings) of it, that is in tensorflow dataset format, and
